name: Editor Build

on:
  push:
  pull_request:

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-11]
        include:
        - name: "Windows x64"
          os: windows-latest
          cmake-args: -G "Visual Studio 16 2019" -A x64 -DUSE_HARFBUZZ=OFF -DUSE_CONAN=ON
          package-file: "*-win64.zip"
          fancy: false
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

        - name: "Ubuntu x64"
          os: ubuntu-latest
          cmake-args: -G "Unix Makefiles" -DUSE_HARFBUZZ=OFF -DUSE_CONAN=OFF
          build-args: --parallel
          package-file: "*.zip"
          env:
            CFLAGS: -Wdeclaration-after-statement -Wduplicated-branches -Werror
            CXXFLAGS: -Wduplicated-branches -Wno-error

        - name: "macOS 11"
          os: macos-11
          cmake-args: -G "Unix Makefiles" -DUSE_HARFBUZZ=OFF -DUSE_CONAN=ON
          build-args: --parallel
          package-file: "*.zip"
          env:
            CFLAGS: -Wdeclaration-after-statement
            CXXFLAGS: -Wduplicated-branches -Wno-error

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install pkg-config cmake libfreetype6-dev libsdl2-dev libicu-dev libssl-dev libcurl4-openssl-dev -y
        sudo apt-get install libboost-dev libmariadbclient-dev libmysqlcppconn-dev libopus-dev libopusfile-dev -y

    - name: Build in release mode
      env: ${{ matrix.env }}
      run: |
        mkdir release
        cd release
        ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release ..
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }}

    - name: Package
      run: |
        cd release
        ${{ matrix.cmake-path }}cmake --build . --config Release --target package ${{ matrix.build-args }}
        mkdir artifacts
        mv ${{ matrix.package-file }} artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: teeuniverse-${{ matrix.os }}
        path: release/artifacts
